apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: verysecretpassword!
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: archimedes-data-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: archimedes-data-persistent-storage
        persistentVolumeClaim:
          claimName: archimedes-mysql-pv-claim


